(cl:in-package #:climacs-syntax-common-lisp)

(defun cached-parse-result (analyzer-stream)
  (let* ((analyzer (analyzer analyzer-stream))
	 (residue (residue analyzer))
	 (suffix (suffix analyzer)))
    (cond ((not (null residue))
	   (if (and (= (start-line (first residue))
		       (current-line analyzer-stream))
		    (= (start-column (first residue))
		       (current-column analyzer-stream)))
	       (first residue)
	       nil))
	  ((not (null suffix))
	   (if (and (= (start-line (first suffix))
		       (current-line analyzer-stream))
		    (= (start-column (first suffix))
		       (current-column analyzer-stream)))
	       (first suffix)
	       nil))
	  (t nil))))

(defun advance-stream-to-beyond-parse-result (analyzer-stream parse-result)
  (setf (current-line analyzer-stream)
	(+ (start-line parse-result)
	   (end-line parse-result)))
  (setf (current-column analyzer-stream)
	(end-column parse-result))
  (read-char input-stream nil nil))

