(cl:in-package #:climacs-syntax-common-lisp)

(defun read-forms (analyzer)
  (loop with cache = (folio analyzer)
	do (if (or (null (suffix cache))
		   (and (= (current-line-number analyzer)
			   (start-line (first (suffix cache))))
			(= (current-item-number analyzer)
			   (start-column (first (suffix cache))))))
	       ;; The suffix is either empty or consists of a list of
	       ;; top-level parse results.
	       (return-from read-forms nil)
	       (let ((next (parse analyzer)))
		 (loop until (or (null (residue cache))
				 (> (start-line (first (residue cache)))
				    (current-line-number analyzer))
				 (and (= (start-line (first (residue cache)))
					 (current-line-number analyzer))
				      (> (start-column (first (residue cache)))
					 (current-item-number analyzer))))
		       do (pop (residue cache)))
		 (when (null (residue cache))
		   (loop until (or (null (suffix cache))
				   (> (start-line (first (suffix cache)))
				      (current-line-number analyzer))
				   (and (= (start-line (first (suffix cache)))
					   (current-line-number analyzer))
					(> (start-column (first (suffix cache)))
					   (current-item-number analyzer))))
			 do (pop-from-suffix cache)))
		 (push next (prefix cache))))))
