(cl:in-package #:climacs-syntax-common-lisp)

(defun read-forms (analyzer-stream)
  (loop with analyzer = (folio analyzer-stream)
	do (if (or (null (suffix analyzer))
		   (and (= (current-line-number analyzer-stream)
			   (start-line (first (suffix analyzer))))
			(= (current-item-number analyzer-stream)
			   (start-column (first (suffix analyzer))))))
	       ;; The suffix is either empty or consists of a list of
	       ;; top-level parse results.
	       (return-from read-forms nil)
	       (let ((next (parse analyzer-stream)))
		 (loop until (or (null (residue analyzer))
				 (> (start-line (first (residue analyzer)))
				    (current-line-number analyzer-stream))
				 (and (= (start-line (first (residue analyzer)))
					 (current-line-number analyzer-stream))
				      (> (start-column (first (residue analyzer)))
					 (current-item-number analyzer-stream))))
		       do (pop (residue analyzer)))
		 (when (null (residue analyzer))
		   (loop until (or (null (suffix analyzer))
				   (> (start-line (first (suffix analyzer)))
				      (current-line-number analyzer-stream))
				   (and (= (start-line (first (suffix analyzer)))
					   (current-line-number analyzer-stream))
					(> (start-column (first (suffix analyzer)))
					   (current-item-number analyzer-stream))))
			 do (pop-from-suffix analyzer)))
		 (push next (prefix analyzer))))))
