#!/bin/sh

NAME=$0
TITLE="Inserting and deleting a left parenthesis"
OUTPUT=eps

gnuplot << _EOF_
set terminal postscript eps color
set output "$NAME.$OUTPUT"
set title "$TITLE"
set key off inside center top
set xlabel "nb forms"
set ylabel "Time in ms"

plot '$NAME.res' using 1:3 with lines lc rgb 'green' # dt 2
_EOF_
