#!/bin/sh

NAME=$0
TITLE="Inserting and deleting a constituent character"
OUTPUT=eps

gnuplot << _EOF_
set terminal postscript eps color
set output "$NAME.$OUTPUT"
set title "$TITLE"
set key off inside center top
set xlabel "nb forms X form size (lines)"
set ylabel "Time in ms"

plot '$NAME.res' using (\$1*\$2):3 with lines lc rgb 'blue' # dt 2
_EOF_
